version: "3.9"
services:
  db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: Levi
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  bot:
    container_name: LeviBot
    restart: always
    env_file:
      - ./.env
    build: .
    depends_on:
      - db

volumes:
  pgdata:
